# railway.toml
[build]
builder = "Dockerfile"

[deploy]
start = "npm run preview"  # Runs the Vite preview command for the production build
healthcheck = "/"

[service]
name = "vite-react-app"
envs = { PORT = "5000" }
